#!/bin/sh

cd $ZOOKEEPER_HOME

#Start zookeeper
bin/zkServer.sh start


cd $KAFKA_HOME/config

#------------------------------------Configure server properties-----------------------------------------------#
#cat server.properties |
cat server.properties | sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-1/"> server-1.properties 
cat server.properties | sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-2/"> server-2.properties 
cat server.properties | sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-3/"> server-3.properties 
cat server.properties | sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-4/"> server-4.properties 
cat server.properties | sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-5/"> server-5.properties 
echo "Server 1-5 properties completed"
#cat server-1.properties |
cat server-1.properties | sed -e "s/broker.id=0/broker.id=1/" > server_1.properties
cat server-2.properties | sed -e "s/broker.id=0/broker.id=2/" > server_2.properties
cat server-3.properties | sed -e "s/broker.id=0/broker.id=3/" > server_3.properties
cat server-4.properties | sed -e "s/broker.id=0/broker.id=4/" > server_4.properties
cat server-5.properties | sed -e "s/broker.id=0/broker.id=5/" > server_5.properties
echo "Broker id assigned"

echo -e "\nlisteners=PLAINTEXT://:9091" >> server_1.properties
echo -e "\nlisteners=PLAINTEXT://:9092" >> server_2.properties
echo -e "\nlisteners=PLAINTEXT://:9093" >> server_3.properties
echo -e "\nlisteners=PLAINTEXT://:9094" >> server_4.properties
echo -e "\nlisteners=PLAINTEXT://:9095" >> server_5.properties
echo -e "\nBroker port assigned"

rm server-1.properties
rm server-2.properties
rm server-3.properties
rm server-4.properties
rm server-5.properties

#-----------------------------------End of configurations-------------------------------------------------------#

cd $KAFKA_HOME

echo "starting up kafka servers"
#Start brokers
kafka-server-start.sh -daemon $KAFKA_HOME/config/server_1.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server_2.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server_3.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server_4.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server_5.properties
echo "kafka servers started"
