#!/bin/sh

#Go to opt dir
cd /opt/

#Get the software 
wget http://mirrors.ibiblio.org/apache/kafka/2.3.1/kafka-2.3.1-src.tgz

#Add config files
echo -e '#Set up Kafka\nexport KAFKA_HOME=/home/opt/kafka-2.3.1-src\nexport PATH=$PATH:$KAFKA_HOME/bin' >> .bash_profile



