#!/bin/sh

#Start Hadoop
source /home/cliff/startHadoop.sh

#Change to task 14
cd /home/cliff/notes/Task-14

#Python to get data
python getChuckNorris.py

#send to hdfs
hadoop fs -copyFromLocal data.json /data

