#!/bin/sh

#Get flume
wget http://apache-mirror.8birdsvideo.com/flume/1.9.0/apache-flume-1.9.0-bin.tar.gz
#Extract the file
tar -xzvf apache-flume-1.9.0-bin.tar.gz
#Move
sudo mv apache-flume-1.9.0-bin /home/opt

#Update the bash profile
echo 'export FLUME_HOME=/home/opt/apache-flume-1.9.0-bin' >> ~/.bash_profile
echo 'export PATH=$PATH:$FLUME_HOME/bin' >> ~/.bash_profile


