create table funny_table (registration_dttm 	timestamp,
id 			int,
first_name 		varchar,
last_name 		varchar,
email 			varchar,
gender 			varchar,
ip_address 		varchar,
cc 			varchar,
country 		varchar,
birthdate 		varchar,
salary 			float,
title 			varchar,
comments  varchar(500) );
