#!/bin/bash
source ~/.bash_profile

cd $ZOOKEEPER_HOME

#Start zookeeper
bin/zkServer.sh start


cd $KAFKA_HOME/config

#create 5 server
cp server.properties server-1.properties
cp server.properties server-2.properties
cp server.properties server-3.properties
cp server.properties server-4.properties
cp server.properties server-5.properties

sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-1/"> server-1.properties 
sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-2/"> server-2.properties 
sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-3/"> server-3.properties 
sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-4/"> server-4.properties 
sed -e "s/log.dirs=\/tmp\/kafka-logs/log.dirs=\/tmp\/kafka-logs-5/"> server-5.properties 

sed -e "s/broker.id=0/broker.id=1" > server-1.properties
sed -e "s/broker.id=0/broker.id=2" > server-2.properties
sed -e "s/broker.id=0/broker.id=3" > server-3.properties
sed -e "s/broker.id=0/broker.id=4" > server-4.properties
sed -e "s/broker.id=0/broker.id=5" > server-5.properties


echo "listeners=PLAINTEXT://:9091" >> server-1.properties
echo "listeners=PLAINTEXT://:9092" >> server-2.properties
echo "listeners=PLAINTEXT://:9093" >> server-3.properties
echo "listeners=PLAINTEXT://:9094" >> server-4.properties
echo "listeners=PLAINTEXT://:9095" >> server-5.properties

cd $KAFKA_HOME

#Start brokers
kafka-server-start.sh -daemon $KAFKA_HOME/config/server-1.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server-2.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server-3.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server-4.properties
kafka-server-start.sh -daemon $KAFKA_HOME/config/server-5.properties
